name: amls2_proj
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - albumentations=1.3.0
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - cryptography=39.0.1
  - cuda-cccl=12.1.55
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.1.55
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.3.2
  - eigen=3.4.0
  - enum34=1.1.10
  - fftw=3.3.9
  - filelock=3.9.0
  - flit-core=3.8.0
  - freetype=2.10.4
  - fsspec=2023.3.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imagecodecs-lite=2019.12.3
  - imageio=2.27.0
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.6
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.2.56
  - libcurand-dev=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.17
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.4
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - msys2-conda-epoch=20160418
  - networkx=2.8.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - opencv=4.6.0
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - packaging=23.0
  - pandas=1.5.2
  - partd=1.3.0
  - pathlib=1.0.1
  - pcre=8.45
  - pip=22.3.1
  - platformdirs=2.6.2
  - pooch=1.7.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - qudida=0.0.4
  - requests=2.28.1
  - scikit-image=0.18.1
  - scikit-learn=1.2.0
  - scipy=1.10.0
  - seaborn=0.12.2
  - tifffile=2021.4.8
  - tqdm=4.65.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - pip:
      - openslide-python==1.2.0
      - pillow==9.4.0
      - torchaudio==2.0.0
      - torchvision==0.15.0
